version: "3.8"
services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    ports:
      - 27017:27017
    networks:
      - mongo-network
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    ports:
      - 27018:27017
    networks:
      - mongo-network
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    ports:
      - 27019:27017
    networks:
      - mongo-network
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

networks:
  mongo-network:
    driver: bridge
