version: '3.9'
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_SEEDS: "cassandra1"
      CASSANDRA_LISTEN_ADDRESS: "cassandra1"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      MAX_HEAP_SIZE: "1G"
      HEAP_NEWSIZE: "256M"
    volumes:
      - cassandra1_data:/var/lib/cassandra
    networks:
      cassandra_network:
        aliases:
          - cassandra1

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_SEEDS: "cassandra1"
      CASSANDRA_LISTEN_ADDRESS: "cassandra2"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra2"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      CASSANDRA_AUTO_BOOTSTRAP: "false" # Отключаем авто-бутстрап
      MAX_HEAP_SIZE: "1G"
      HEAP_NEWSIZE: "256M"
    volumes:
      - cassandra2_data:/var/lib/cassandra
    networks:
      cassandra_network:
        aliases:
          - cassandra2

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_SEEDS: "cassandra1"
      CASSANDRA_LISTEN_ADDRESS: "cassandra3"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra3"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      CASSANDRA_AUTO_BOOTSTRAP: "false" # Отключаем авто-бутстрап
      MAX_HEAP_SIZE: "1G"
      HEAP_NEWSIZE: "256M"
    volumes:
      - cassandra3_data:/var/lib/cassandra
    networks:
      cassandra_network:
        aliases:
          - cassandra3

networks:
  cassandra_network:
    driver: bridge

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data:
